# Generated by Django 6.0.5 on 2026-08-13 06:18

import apps.masters.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.CharField(default=apps.masters.models.pk_cat, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.CharField(default=apps.masters.models.pk_itm, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.mastercategory')),
            ],
            options={
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='MasterItemVersion',
            fields=[
                ('id', models.CharField(default=apps.masters.models.pk_ver, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('version_no', models.IntegerField(default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='masters.masteritem')),
            ],
        ),
    ]
