# Generated by Django 6.0.5 on 2026-08-13 15:58

import apps.masters.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_permission_options_permission_can_approve_and_more'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='mastercategory',
            name='owning_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_categories', to='core.department'),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_items', to='core.department'),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_items', to='core.plant'),
        ),
        migrations.CreateModel(
            name='MasterAttributeDefinition',
            fields=[
                ('id', models.CharField(default=apps.masters.models.pk_mad, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('attribute_code', models.CharField(max_length=80)),
                ('attribute_name', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('reference', 'Reference FK')], max_length=20)),
                ('reference_table', models.CharField(blank=True, choices=[('storage_location', 'Storage Location'), ('machine', 'Machine / Vehicle'), ('vendor', 'Vendor'), ('employee', 'Employee'), ('master_item', 'Master Item'), ('process_instance', 'Process Instance')], max_length=80, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='masters.mastercategory')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('master_category', 'attribute_code')},
            },
        ),
        migrations.CreateModel(
            name='MasterAttributeValue',
            fields=[
                ('id', models.CharField(default=apps.masters.models.pk_mav, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='masters.masterattributedefinition')),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='masters.masteritem')),
            ],
            options={
                'unique_together': {('master_item', 'attribute_definition')},
            },
        ),
    ]
