# Generated by Django 6.0.5 on 2026-08-13 16:22

import apps.masters.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_permission_options_permission_can_approve_and_more'),
        ('masters', '0002_mastercategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterattributevalue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MasterAttribute',
            fields=[
                ('id', models.CharField(default=apps.masters.models.pk_mat, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('attribute_code', models.CharField(max_length=80)),
                ('attribute_name', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('reference', 'Reference FK')], default='text', max_length=20)),
                ('reference_table', models.CharField(blank=True, choices=[('storage_location', 'Storage Location'), ('machine', 'Machine / Vehicle'), ('vendor', 'Vendor'), ('employee', 'Employee'), ('master_item', 'Master Item'), ('master_instance', 'Master Instance'), ('process_instance', 'Process Instance')], max_length=80, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='masters.mastercategory')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('master_category', 'attribute_code')},
            },
        ),
        migrations.AddField(
            model_name='masterattributevalue',
            name='master_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='masters.masterattribute'),
        ),
        migrations.CreateModel(
            name='MasterInstance',
            fields=[
                ('id', models.CharField(default=apps.masters.models.pk_msc, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_instances', to='core.department')),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='masters.mastercategory')),
                ('master_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='masters.masteritem')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_instances', to='core.plant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='masterattributevalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='masterattributevalue',
            name='master_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='masters.masterinstance'),
        ),
        migrations.AlterUniqueTogether(
            name='masterattributevalue',
            unique_together={('master_instance', 'master_attribute')},
        ),
        migrations.RemoveField(
            model_name='masterattributevalue',
            name='attribute_definition',
        ),
        migrations.RemoveField(
            model_name='masterattributevalue',
            name='master_item',
        ),
        migrations.DeleteModel(
            name='MasterAttributeDefinition',
        ),
    ]
