# Generated by Django 6.0.5 on 2026-08-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_masterattributevalue_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterattribute',
            name='options',
            field=models.TextField(blank=True, help_text='Comma separated options for select dropdown', null=True),
        ),
        migrations.AlterField(
            model_name='masterattribute',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('select', 'Dropdown'), ('reference', 'Reference FK'), ('email', 'Email'), ('phone', 'Phone'), ('currency', 'Currency'), ('file', 'File'), ('url', 'URL'), ('password', 'Password')], default='text', max_length=20),
        ),
    ]
