# Generated by Django 6.0.5 on 2026-08-13 06:18

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_coa, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_cmp, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_dpt, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('is_shared_across_plants', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_rol, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_vnd, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_info', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_dsg, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('hierarchy_level', models.IntegerField(default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_emp, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('user_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_doc, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('entity_table', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('version_no', models.IntegerField(default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBankAccount',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_bnk, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=40)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_edt, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_pln, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('plant_type', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('transport', 'Transport')], default='manufacturing', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_mac, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('machine_type_id', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('capacity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('fastag_number', models.CharField(blank=True, max_length=30, null=True)),
                ('fastag_status', models.CharField(blank=True, default='active', max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='active', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='core.department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='core.plant')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.plant'),
        ),
        migrations.AddField(
            model_name='department',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.plant'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_prm, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=40)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.role')),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocationBlock',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_blk, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('start_code', models.CharField(max_length=4)),
                ('end_code', models.CharField(max_length=4)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_emr, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.role')),
            ],
            options={
                'unique_together': {('employee', 'role')},
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_bin, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4)),
                ('capacity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='core.department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='core.plant')),
                ('storage_location_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.storagelocationblock')),
            ],
            options={
                'unique_together': {('plant', 'code')},
            },
        ),
    ]
