# Generated by Django 6.0.5 on 2026-08-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_department_alter_employee_designation'),
        ('masters', '0001_initial'),
        ('process_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='permission',
            name='can_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.designation'),
        ),
        migrations.AddField(
            model_name='permission',
            name='master_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='masters.mastercategory'),
        ),
        migrations.AddField(
            model_name='permission',
            name='process_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='process_engine.processtype'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.role'),
        ),
    ]
