# Generated by Django 6.0.5 on 2026-08-15 07:25

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_permission_options_permission_can_approve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIForm',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_frm, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('form_name', models.CharField(max_length=100, unique=True)),
                ('module', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ui_form',
            },
        ),
        migrations.CreateModel(
            name='UINavbar',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_nav, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('show_search', models.BooleanField(default=True)),
                ('show_notification', models.BooleanField(default=True)),
                ('show_profile', models.BooleanField(default=True)),
                ('show_logout', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ui_navbar',
            },
        ),
        migrations.CreateModel(
            name='UITheme',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_thm, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('theme_name', models.CharField(max_length=100, unique=True)),
                ('primary_color', models.CharField(default='#3b82f6', max_length=30)),
                ('secondary_color', models.CharField(default='#6366f1', max_length=30)),
                ('background_color', models.CharField(default='#0f172a', max_length=30)),
                ('card_bg_color', models.CharField(default='#1e293b', max_length=30)),
                ('text_color', models.CharField(default='#f8fafc', max_length=30)),
                ('border_color', models.CharField(default='rgba(255,255,255,0.1)', max_length=30)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ui_theme',
            },
        ),
        migrations.CreateModel(
            name='UIWidget',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_wgt, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('widget_name', models.CharField(max_length=150)),
                ('widget_type', models.CharField(choices=[('kpi', 'KPI Metric Card'), ('chart_bar', 'Bar Chart'), ('chart_pie', 'Pie Chart'), ('table', 'Summary Table'), ('list', 'Activity List'), ('shortcut', 'Quick Shortcut')], default='kpi', max_length=50)),
                ('data_source', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.IntegerField(default=0)),
                ('grid_width', models.CharField(default='col-span-1', max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ui_widget',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='UIFormField',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_fld, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=150)),
                ('field_code', models.CharField(max_length=80)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('select', 'Dropdown'), ('reference', 'Reference FK'), ('email', 'Email'), ('phone', 'Phone'), ('currency', 'Currency'), ('file', 'File Upload'), ('url', 'URL'), ('password', 'Password')], default='text', max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('options', models.TextField(blank=True, help_text='Comma separated choices for dropdown', null=True)),
                ('reference_table', models.CharField(blank=True, max_length=80, null=True)),
                ('field_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.uiform')),
            ],
            options={
                'db_table': 'ui_form_field',
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='UIMenu',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_mnu, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=150)),
                ('menu_path', models.CharField(max_length=200)),
                ('module_code', models.CharField(max_length=80)),
                ('menu_icon', models.CharField(default='LayoutDashboard', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submenus', to='core.uimenu')),
            ],
            options={
                'db_table': 'ui_menu',
                'ordering': ['display_order', 'menu_name'],
            },
        ),
        migrations.CreateModel(
            name='UIModal',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_mdl, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('modal_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('width', models.CharField(default='600px', max_length=30)),
                ('height', models.CharField(default='auto', max_length=30)),
                ('submit_text', models.CharField(default='Submit', max_length=50)),
                ('cancel_text', models.CharField(default='Cancel', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modals', to='core.uiform')),
            ],
            options={
                'db_table': 'ui_modal',
            },
        ),
        migrations.CreateModel(
            name='UIMenuPermission',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_mnp, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('permission', models.CharField(default='view', max_length=50)),
                ('can_view', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.uimenu')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='core.role')),
            ],
            options={
                'db_table': 'ui_menu_permission',
                'unique_together': {('menu', 'role', 'permission')},
            },
        ),
    ]
