# Generated by Django 6.0.5 on 2026-08-17 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_uiform_uinavbar_uitheme_uiwidget_uiformfield_uimenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='core.department'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='core.department'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='core.plant'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='core.company'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing'), ('processing', 'Processing Unit'), ('packaging', 'Packaging Warehouse'), ('storage', 'Central Cold Storage'), ('transport', 'Transport')], default='manufacturing', max_length=30),
        ),
    ]
