# Generated by Django 6.0.5 on 2026-08-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_designation_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storagelocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='unit_id',
            field=models.CharField(blank=True, help_text='Unit ID or Plant Code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_locations', to='core.department'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_locations', to='core.plant'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='storage_location_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.storagelocationblock'),
        ),
    ]
