# Generated by Django 5.0.14 on 2026-08-17 17:13

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_storagelocation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAuditLog',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_alg, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('config_type', models.CharField(help_text='menu, navbar, theme, form, widget, etc.', max_length=60)),
                ('item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('TOGGLE', 'Toggled Status'), ('RESTORE', 'Restored Version')], default='UPDATE', max_length=30)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('changed_by_name', models.CharField(default='System Super Administrator', max_length=150)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ui_config_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_ver, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('config_type', models.CharField(max_length=60)),
                ('snapshot_data', models.JSONField()),
                ('created_by_name', models.CharField(default='System Super Administrator', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ui_config_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='uitheme',
            name='accent_color',
            field=models.CharField(blank=True, default='#06b6d4', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='button_radius',
            field=models.CharField(blank=True, default='6px', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='font_family',
            field=models.CharField(blank=True, default='Inter, sans-serif', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='navbar_color',
            field=models.CharField(blank=True, default='#0f172a', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='sidebar_color',
            field=models.CharField(blank=True, default='#1e293b', max_length=30, null=True),
        ),
    ]
