# Generated by Django 5.0.14 on 2026-08-17 18:41

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


def seed_control_center(apps, schema_editor):
    SearchConfig = apps.get_model('core', 'GlobalSearchConfiguration')
    DashboardLayout = apps.get_model('core', 'UIDashboardLayout')
    definitions = [
        ('companies', 'Companies', 'structural_masters', 'core.Company', ['id', 'name', 'gst_number', 'remarks'], ['name', 'id', 'gst_number'], '', '/structural-masters'),
        ('employees', 'Employees', 'structural_masters', 'core.Employee', ['id', 'name', 'status', 'user_account_id', 'designation__title', 'department__name'], ['name', 'id', 'designation__title'], 'status', '/structural-masters'),
        ('vendors', 'Vendors', 'structural_masters', 'core.Vendor', ['id', 'name', 'gst_number', 'remarks'], ['name', 'id', 'gst_number'], '', '/structural-masters'),
        ('machines', 'Machines', 'structural_masters', 'core.Machine', ['id', 'code', 'name', 'registration_number', 'status'], ['name', 'code', 'registration_number'], 'status', '/structural-masters'),
        ('storage_locations', 'Storage Locations', 'structural_masters', 'core.StorageLocation', ['id', 'code', 'name', 'status', 'department__name'], ['code', 'name', 'department__name'], 'status', '/structural-masters'),
        ('accounts', 'Chart of Accounts', 'structural_masters', 'core.ChartOfAccount', ['id', 'code', 'name', 'account_type'], ['name', 'code', 'account_type'], 'account_type', '/structural-masters'),
        ('master_categories', 'Master Categories', 'dynamic_masters', 'masters.MasterCategory', ['id', 'code', 'name', 'remarks'], ['name', 'code'], '', '/dynamic-masters'),
        ('master_items', 'Products / Master Items', 'dynamic_masters', 'masters.MasterItem', ['id', 'code', 'name', 'category__name', 'remarks'], ['name', 'code', 'category__name'], '', '/dynamic-masters'),
        ('process_types', 'Process Types', 'process_engine', 'process_engine.ProcessType', ['id', 'code', 'name', 'category', 'remarks'], ['name', 'code', 'category'], 'category', '/process-engine'),
        ('process_instances', 'Process Executions', 'process_engine', 'process_engine.ProcessInstance', ['id', 'status', 'remarks', 'process_type__name', 'process_type__code'], ['id', 'process_type__name', 'status'], 'status', '/process-engine'),
        ('proposals', 'Workflow Proposals', 'workflow', 'workflow.Proposal', ['id', 'status', 'remarks', 'requested_by__name', 'process_instance__id'], ['id', 'requested_by__name', 'status'], 'status', '/workflow-approvals'),
        ('journal_entries', 'Journal Entries', 'journal', 'journal.JournalEntry', ['id', 'material_id', 'movement_type', 'entry_date', 'remarks', 'vendor__name'], ['id', 'material_id', 'movement_type'], 'movement_type', '/journal-stock'),
        ('stock', 'Stock Ledger', 'journal', 'journal.Stock', ['id', 'material_id', 'stock_status', 'quantity', 'unit_id', 'storage_location__code'], ['material_id', 'storage_location__code', 'quantity'], 'stock_status', '/journal-stock'),
    ]
    for priority, definition in enumerate(definitions, start=10):
        key, name, module, label, searchable, display, status, route = definition
        SearchConfig.objects.get_or_create(entity_key=key, defaults={
            'id': f'SRC-SEED-{priority:03d}',
            'display_name': name, 'module': module, 'model_label': label,
            'searchable_fields': searchable, 'display_fields': display,
            'status_field': status, 'route': route, 'result_priority': priority,
            'result_limit': 10, 'match_mode': 'contains', 'active': True,
        })
    DashboardLayout.objects.get_or_create(role=None, layout_name='Default Dashboard', defaults={
        'id': 'DBL-SEED-DEFAULT',
        'layout_mode': 'grid', 'desktop_columns': 4, 'tablet_columns': 2,
        'mobile_columns': 1, 'row_gap': 16, 'column_gap': 16,
        'widget_height': 'auto', 'responsive': True, 'active': True,
    })


def unseed_control_center(apps, schema_editor):
    apps.get_model('core', 'GlobalSearchConfiguration').objects.filter(
        entity_key__in=['companies', 'employees', 'vendors', 'machines', 'storage_locations', 'accounts', 'master_categories', 'master_items', 'process_types', 'process_instances', 'proposals', 'journal_entries', 'stock']
    ).delete()
    apps.get_model('core', 'UIDashboardLayout').objects.filter(role=None, layout_name='Default Dashboard').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_uiwidget_refresh_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='configauditlog',
            name='module',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='configauditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='configauditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='configversion',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configversion',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uiformfield',
            name='column_span',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='uiformfield',
            name='conditional_field',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='uiformfield',
            name='conditional_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uiformfield',
            name='help_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uiformfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uiformfield',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='uiformfield',
            name='min_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uiformfield',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='uiformfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uiformfield',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uiformfield',
            name='validation_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uiformfield',
            name='validation_regex',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='application_name',
            field=models.CharField(default='ERP v3', max_length=120),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='danger_color',
            field=models.CharField(default='#dc2626', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='info_color',
            field=models.CharField(default='#2563eb', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='input_background_color',
            field=models.CharField(default='#ffffff', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='input_border_color',
            field=models.CharField(default='#d1d5db', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='input_text_color',
            field=models.CharField(default='#1f2937', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='login_background_color',
            field=models.CharField(default='#f8fafc', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='login_card_color',
            field=models.CharField(default='#ffffff', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='logo_text',
            field=models.CharField(default='E3', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='menu_spacing',
            field=models.CharField(default='4px', max_length=20),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='navbar_border_color',
            field=models.CharField(default='#e2e8f0', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='navbar_icon_color',
            field=models.CharField(default='#475569', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='navbar_text_color',
            field=models.CharField(default='#0f172a', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='shadow_value',
            field=models.CharField(default='0 2px 8px rgba(15,23,42,0.08)', max_length=120),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='sidebar_active_bg',
            field=models.CharField(default='rgba(255,255,255,0.18)', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='sidebar_active_icon_color',
            field=models.CharField(default='#ffffff', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='sidebar_active_text',
            field=models.CharField(default='#ffffff', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='sidebar_border_color',
            field=models.CharField(default='rgba(255,255,255,0.1)', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='sidebar_collapsed_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='sidebar_hover_bg',
            field=models.CharField(default='rgba(255,255,255,0.10)', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='sidebar_hover_text',
            field=models.CharField(default='#ffffff', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='sidebar_icon_color',
            field=models.CharField(default='#dbeafe', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='sidebar_text_color',
            field=models.CharField(default='#ffffff', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='sidebar_width',
            field=models.CharField(default='250px', max_length=20),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='success_color',
            field=models.CharField(default='#16a34a', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='table_header_color',
            field=models.CharField(default='#f8fafc', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='table_row_color',
            field=models.CharField(default='#ffffff', max_length=30),
        ),
        migrations.AddField(
            model_name='uitheme',
            name='warning_color',
            field=models.CharField(default='#f6ce0a', max_length=30),
        ),
        migrations.AddField(
            model_name='uiwidget',
            name='collapsible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uiwidget',
            name='default_collapsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uiwidget',
            name='height',
            field=models.CharField(default='auto', max_length=30),
        ),
        migrations.AddField(
            model_name='uiwidget',
            name='max_width',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='uiwidget',
            name='min_width',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='uiwidget',
            name='module',
            field=models.CharField(default='dashboard', max_length=80),
        ),
        migrations.AddField(
            model_name='uiwidget',
            name='permission_module',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='uiwidget',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='dashboard_widgets', to='core.role'),
        ),
        migrations.AlterField(
            model_name='configauditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('TOGGLE', 'Toggled Status'), ('RESTORE', 'Restored Version'), ('ENABLE', 'Enabled'), ('DISABLE', 'Disabled'), ('ROLLBACK', 'Rolled Back'), ('PUBLISH', 'Published')], default='UPDATE', max_length=30),
        ),
        migrations.AlterField(
            model_name='uiformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('select', 'Dropdown'), ('reference', 'Reference FK'), ('email', 'Email'), ('phone', 'Phone'), ('currency', 'Currency'), ('file', 'File Upload'), ('url', 'URL'), ('password', 'Password'), ('decimal', 'Decimal'), ('multiselect', 'Multi-select'), ('radio', 'Radio Group'), ('image', 'Image Upload'), ('relationship', 'Relationship')], default='text', max_length=30),
        ),
        migrations.CreateModel(
            name='GlobalSearchConfiguration',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_src, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('entity_key', models.CharField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('module', models.CharField(max_length=80)),
                ('model_label', models.CharField(max_length=120)),
                ('searchable_fields', models.JSONField(default=list)),
                ('display_fields', models.JSONField(blank=True, default=list)),
                ('status_field', models.CharField(blank=True, default='', max_length=120)),
                ('route', models.CharField(max_length=200)),
                ('result_priority', models.PositiveIntegerField(default=100)),
                ('result_limit', models.PositiveSmallIntegerField(default=10)),
                ('match_mode', models.CharField(choices=[('contains', 'Contains'), ('starts_with', 'Starts With'), ('exact', 'Exact')], default='contains', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='search_configurations', to='core.role')),
            ],
            options={
                'db_table': 'global_search_configuration',
                'ordering': ['result_priority', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='UIDashboardLayout',
            fields=[
                ('id', models.CharField(default=apps.core.models.pk_dbl, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('layout_name', models.CharField(default='Default Dashboard', max_length=120)),
                ('layout_mode', models.CharField(choices=[('grid', 'Grid'), ('list', 'List'), ('compact', 'Compact'), ('full_width', 'Full Width')], default='grid', max_length=30)),
                ('desktop_columns', models.PositiveSmallIntegerField(default=4)),
                ('tablet_columns', models.PositiveSmallIntegerField(default=2)),
                ('mobile_columns', models.PositiveSmallIntegerField(default=1)),
                ('row_gap', models.PositiveSmallIntegerField(default=16)),
                ('column_gap', models.PositiveSmallIntegerField(default=16)),
                ('widget_height', models.CharField(default='auto', max_length=30)),
                ('responsive', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layouts', to='core.role')),
            ],
            options={
                'db_table': 'ui_dashboard_layout',
                'ordering': ['role_id', 'layout_name'],
            },
        ),
        migrations.RunPython(seed_control_center, unseed_control_center),
    ]
