# Generated by Django 6.0.5 on 2026-08-13 06:18

import apps.workflow.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('process_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChainTemplate',
            fields=[
                ('id', models.CharField(default=apps.workflow.models.pk_act, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('process_type_code', models.CharField(max_length=80)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.CharField(default=apps.workflow.models.pk_prp, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('amended', 'Amended')], default='draft', max_length=30)),
                ('vendor_mode', models.CharField(choices=[('single', 'Single Vendor'), ('multiple', 'Multiple Vendors')], default='single', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.plant')),
                ('process_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='process_engine.processinstance')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_requested', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.CharField(default=apps.workflow.models.pk_stp, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('step_order', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to='core.employee')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='core.designation')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='workflow.proposal')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='ProposalAmendment',
            fields=[
                ('id', models.CharField(default=apps.workflow.models.pk_amd, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amendment_reason', models.TextField()),
                ('previous_values', models.JSONField()),
                ('new_values', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments_made', to='core.employee')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='workflow.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalVendorQuotation',
            fields=[
                ('id', models.CharField(default=apps.workflow.models.pk_quo, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('quoted_rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_selected', models.BooleanField(default=False)),
                ('allocated_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='workflow.proposal')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='core.vendor')),
            ],
        ),
    ]
