# Generated by Django 6.0.5 on 2026-08-17 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_designation_department_and_more'),
        ('process_engine', '0003_alter_processlink_link_type'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='core.department'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='core.plant'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='process_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='process_engine.processinstance'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_requested', to='core.employee'),
        ),
    ]
