# Generated by Django 6.0.5 on 2026-08-13 06:18

import apps.process_engine.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.CharField(default=apps.process_engine.models.pk_prc, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('proposal_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_instances', to='core.department')),
                ('parent_process_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_instances', to='process_engine.processinstance')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_processes', to='core.employee')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_instances', to='core.plant')),
            ],
        ),
        migrations.CreateModel(
            name='AdminVerification',
            fields=[
                ('id', models.CharField(default=apps.process_engine.models.pk_vrf, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Sign-off'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_verifications', to='core.employee')),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='process_engine.processinstance')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessLink',
            fields=[
                ('id', models.CharField(default=apps.process_engine.models.pk_lnk, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('consumes', 'Consumes'), ('pays_for', 'Pays For'), ('fulfills', 'Fulfills'), ('amends', 'Amends'), ('splits_into', 'Splits Into'), ('generates_pay', 'Generates Pay'), ('verifies', 'Verifies')], max_length=60)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='process_engine.processinstance')),
                ('to_process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='process_engine.processinstance')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.CharField(default=apps.process_engine.models.pk_pct, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('qc', 'Quality Control'), ('production', 'Production'), ('packaging', 'Packaging'), ('purchase', 'Purchase'), ('transport', 'Transport'), ('hr', 'HR & Payroll'), ('finance', 'Finance'), ('admin', 'Admin & Maintenance')], default='qc', max_length=40)),
                ('requires_approval', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owning_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_types', to='core.department')),
            ],
        ),
        migrations.AddField(
            model_name='processinstance',
            name='process_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='process_engine.processtype'),
        ),
        migrations.CreateModel(
            name='ProcessAttributeDefinition',
            fields=[
                ('id', models.CharField(default=apps.process_engine.models.pk_pad, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('attribute_code', models.CharField(max_length=80)),
                ('attribute_name', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('reference', 'Reference FK')], max_length=20)),
                ('reference_table', models.CharField(blank=True, choices=[('storage_location', 'Storage Location'), ('machine', 'Machine / Vehicle'), ('master_item', 'Master Item'), ('master_item_version', 'Master Item Version'), ('vendor', 'Vendor'), ('employee', 'Employee'), ('process_instance', 'Process Instance')], max_length=80, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='process_engine.processtype')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('process_type', 'attribute_code')},
            },
        ),
        migrations.CreateModel(
            name='ProcessAttributeValue',
            fields=[
                ('id', models.CharField(default=apps.process_engine.models.pk_pav, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='process_engine.processattributedefinition')),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='process_engine.processinstance')),
            ],
            options={
                'unique_together': {('process_instance', 'attribute_definition')},
            },
        ),
    ]
