# Generated by Django 6.0.5 on 2026-08-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_engine', '0002_processattributedefinition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlink',
            name='link_type',
            field=models.CharField(choices=[('consumes', 'Consumes'), ('pays_for', 'Pays For'), ('fulfills', 'Fulfills'), ('amends', 'Amends'), ('splits_into', 'Splits Into'), ('generates_pay', 'Generates Pay'), ('verifies', 'Verifies'), ('settles', 'Settles')], max_length=60),
        ),
    ]
