# Generated by Django 6.0.5 on 2026-08-13 06:18

import apps.journal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('process_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.CharField(default=apps.journal.models.pk_jrn, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('movement_type', models.CharField(choices=[('internal', 'Internal Department Transfer'), ('external_in', 'External Receipt (Vendor Inward)'), ('external_out', 'External Dispatch (Customer Outward)')], max_length=40)),
                ('material_id', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('value_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.chartofaccount')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_from_depts', to='core.department')),
                ('from_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_from_plants', to='core.plant')),
                ('from_storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_from_bins', to='core.storagelocation')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journals', to='core.employee')),
                ('process_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='process_engine.processinstance')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_to_depts', to='core.department')),
                ('to_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_to_plants', to='core.plant')),
                ('to_storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_to_bins', to='core.storagelocation')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(default=apps.journal.models.pk_stk, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('material_id', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=16)),
                ('unit_id', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_status', models.CharField(default='available', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.plant')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.storagelocation')),
            ],
            options={
                'unique_together': {('plant', 'department', 'material_id', 'storage_location')},
            },
        ),
    ]
