# Generated by Django 6.0.5 on 2026-08-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='unit',
            field=models.CharField(blank=True, default='KG', max_length=50, null=True),
        ),
    ]
